# Site settings
title: Blog - Polyana Pimenta
first_name: Polyana
last_name: Pimenta
email: polyanapimenta@gmail.com
description:
  Meu blog pessoal para estudar, codificar e aprender novas tecnologias  
  sobre o desenvolvimento de software. Tudo organizado em um blog para 
  acesso livre a qualquer pessoa e a mim mesma no futuro. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://polyanapimenta.github.io"
linkedin_username: polyanapimenta
github_username:  polyanapimenta
disqus_username: polyanapimenta-github-io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
port: 5001
permalink: /:categories/:title

#Links do menu
url-1: /portifolio
url-2: /tags
url-3: /sobre
url-4: /arquivos